name: Chart build and push

on:
  pull_request:
    paths:
      - 'chart/**'
  push:
    branches:
      - dev
      - staging
    paths:
      - 'chart/**'

jobs:
  check_lint_and_build:
    name: Lint and build the chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set Name and Version
        run: |
          CHART_NAME="osrd-dev"
          CHART_IMAGES_REPOSITORY="edge"
          CHART_IMAGES_VERSION="dev"

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            CHART_VERSION="0.0.1-${{ github.event.pull_request.number }}-${GITHUB_SHA}"
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            CHART_VERSION="0.0.1-dev-${GITHUB_SHA}"
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            CHART_VERSION="0.0.1-staging-${GITHUB_SHA}"
          fi

          echo "CHART_NAME=$CHART_NAME" >> $GITHUB_ENV
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV

          sed -i "s/NAME_REPLACE_ME/$CHART_NAME/" ./chart/Chart.yaml
          sed -i "s/VERSION_REPLACE_ME/$CHART_VERSION/" ./chart/Chart.yaml
          sed -i "s/APP_VERSION_REPLACE_ME/$CHART_IMAGES_VERSION/" ./chart/Chart.yaml
          sed -i "s/REPOSITORY_VERSION_REPLACE_ME/$CHART_IMAGES_REPOSITORY/" ./chart/values.yaml
          sed -i "s/IMAGES_VERSION_REPLACE_ME/$CHART_IMAGES_VERSION/" ./chart/values.yaml

      - name: Lint Helm Chart
        run: helm lint ./chart

      - name: Save and Push Helm Chart to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
          helm package ./chart
          echo "Pushing to oci://ghcr.io/openrailassociation/${CHART_NAME}:${CHART_VERSION}"
          helm push ${CHART_NAME}-${CHART_VERSION}.tgz oci://ghcr.io/openrailassociation/osrd-charts
