name: Publish Helm Chart to GHCR

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        required: true

jobs:
  release:
    if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.event.release.tag_name, 'v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set Name and Version
        run: |
          CHART_NAME="osrd"
          CHART_IMAGES_REPOSITORY="stable"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            CHART_VERSION="${{ github.event.inputs.tag_name }}"
          else
            CHART_VERSION="${{ github.event.release.tag_name }}"
          fi
          CHART_IMAGES_VERSION="${CHART_VERSION}"
          echo "CHART_NAME=$CHART_NAME" >> $GITHUB_ENV
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV
          sed -i "s/NAME_REPLACE_ME/$CHART_NAME/" ./chart/Chart.yaml
          sed -i "s/VERSION_REPLACE_ME/$CHART_VERSION/" ./chart/Chart.yaml
          sed -i "s/APP_VERSION_REPLACE_ME/$CHART_IMAGES_VERSION/" ./chart/Chart.yaml
          sed -i "s/REPOSITORY_VERSION_REPLACE_ME/$CHART_IMAGES_REPOSITORY/" ./chart/values.yaml
          sed -i "s/IMAGES_VERSION_REPLACE_ME/$CHART_IMAGES_VERSION/" ./chart/values.yaml

      - name: Lint Helm Chart
        run: helm lint ./chart

      - name: Save and Push Helm Chart to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
          helm package ./chart
          echo "Pushing to oci://ghcr.io/openrailassociation/osrd-charts/${CHART_NAME}:${CHART_VERSION}"
          helm push ${CHART_NAME}-${CHART_VERSION}.tgz oci://ghcr.io/openrailassociation/osrd-charts
