name: Publish osrd-ui on Release

on:
  release:
    types: [released]

jobs:
  publish:
    if: ${{ startsWith(github.ref, 'refs/tags/ui-v') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v5
        with:
          node-version: "24"

      - name: Authenticate with Registry
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Publish
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          VERSION=${TAG/ui-v/}
          cd front
          npm ci
          scripts/publish-osrd-ui.sh "$VERSION"
