name: pr
on:
  - pull_request_target
jobs:
  label_pr:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: "Label PR"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Label PR
        uses: actions/labeler@v6
        with:
          sync-labels: true
