[formatting]
align_comments = false
reorder_arrays = true

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "dev-dependencies", "workspace.dependencies"]

[rule.formatting]
reorder_keys = true

[[rule]]
include = ["libs.versions.toml"]
keys = ["librairies", "plugins", "versions"]

[rule.formatting]
reorder_keys = true

[[rule]]
include = ["**/pyproject.toml"]
keys = ["dependencies", "project.optional-dependencies", "tool.uv.sources"]

[rule.formatting]
reorder_keys = true
