{{- if .Values.services.editoast.init.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "osrd.fullname" . }}-editoast-init
data:
  script.sh: |
    #!/bin/sh
    set -euo pipefail
    {{- with .Values.services.editoast.init.extend }}
    {{ . | nindent 4 }}
    {{- end }}
    fga_migrations apply && diesel migration run
{{- end }}
