apiVersion: v2
description: A Helm chart for deploying OSRD
type: application
# Replaced by sed in .github/workflows/helm.yaml
appVersion: "APP_VERSION_REPLACE_ME"
name: NAME_REPLACE_ME
version: VERSION_REPLACE_ME
